site_name: My Cloud at the Edge
site_url: https://janvda.github.io/my-cloud-at-the-edge/
site_author: Jan Van den Audenaerde
repo_name: janvda/my-cloud-at-the-edge
repo_url: https://github.com/janvda/my-cloud-at-the-edge
theme:
  name: material
  features:
    - navigation.tabs
plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Page tree
nav:
  - Home: index.md
  - Sessions:
    - Session 1 Intro & Networking: sessions/session_1.md
    - Session 2 (Under Construction): sessions/session_2.md
  - Topics:
    - OpenWrt Router: topics/openwrt_router/README.md
    - OpenWrt Access Point: topics/openwrt_access_point/README.md
    - Raspberry Pi:   topics/raspberry_pi/README.md
    - Intel NUC:      topics/intel_nuc/README.md
